/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package caro.server;

import caro.common.Users;
import caro.database.DataFunc;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ServerSocketFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Cao Ky
 */
public class Main extends javax.swing.JFrame {

    static public ArrayList<ClientHandler> lstClient;
    
    static public ArrayList<Room> lstRoom;
    
    static public ArrayList<Competition> lstCompetition;

    static java.util.List<Users> uslist = new ArrayList<Users>();
    
    static DataFunc df = new DataFunc();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        
        lstCompetition = new ArrayList<Competition>();
        Competition competition = new Competition(txtNameCompetition.getText(), Integer.parseInt(txtNumberUser.getText()));
        lstCompetition.add(competition);
        competition = new Competition(txtNameCompetition.getText() + " 2", Integer.parseInt(txtNumberUser.getText()));
        lstCompetition.add(competition);
        btnRefeshCompetitionMouseClicked(null);
        
        btnRefeshRoomMouseClicked(null);
        
        setTitle("Server - Caro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        bt_del = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        list = new java.awt.List();
        bt_refresh = new javax.swing.JButton();
        btnTop = new javax.swing.JButton();
        btnOnline = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lstCompetitionList = new java.awt.List();
        btnAddCompetition = new javax.swing.JButton();
        txtNameCompetition = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumberUser = new javax.swing.JTextField();
        btnRefeshCompetition = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lstRoomList = new java.awt.List();
        btnRefeshRoom = new javax.swing.JButton();
        btnAddRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bt_del.setText("Delete");
        bt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delActionPerformed(evt);
            }
        });

        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        bt_refresh.setText("Refresh");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        btnTop.setText("TOP Score");
        btnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopActionPerformed(evt);
            }
        });

        btnOnline.setText("Users Online");
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_refresh)
                        .addGap(18, 18, 18)
                        .addComponent(btnTop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOnline)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );

        jTabbedPane1.addTab("Users", jPanel3);

        btnAddCompetition.setText("Add");
        btnAddCompetition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCompetitionMouseClicked(evt);
            }
        });

        txtNameCompetition.setText("World cup");

        jLabel1.setText("Name competition:");

        jLabel2.setText("Number user:");

        txtNumberUser.setText("4");

        btnRefeshCompetition.setText("Refesh");
        btnRefeshCompetition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefeshCompetitionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumberUser))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCompetition)
                .addGap(25, 25, 25)
                .addComponent(btnRefeshCompetition)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lstCompetitionList, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNumberUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAddCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnRefeshCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addComponent(lstCompetitionList, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Competition", jPanel4);

        btnRefeshRoom.setText("Refesh");
        btnRefeshRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefeshRoomMouseClicked(evt);
            }
        });

        btnAddRoom.setText("Add");
        btnAddRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddRoomMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstRoomList, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefeshRoom)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefeshRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lstRoomList, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Room", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         uslist = df.getUserList();
        for (Users users : uslist) {
            list.add("Id: " + users.getId() 
                    +" | Username: " + users.getUsername() 
                    + " | Password: " + users.getPassword() 
                    +" | Win:" +users.getWin()
                    +" | Lose:" +users.getLose()
                    +" | Score:" +users.getScore());
        }                
    }//GEN-LAST:event_formWindowOpened

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        // TODO add your handling code here:

        uslist = df.getUserList();
        list.removeAll();
        for (Users users : uslist) {
            list.add("Id: " + users.getId()
                +" | Username: " + users.getUsername()
                + " | Password: " + users.getPassword()
                +" | Win:" +users.getWin()
                +" | Lose:" +users.getLose()
                +" | Score:" +users.getScore());
        }
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        int indx = list.getSelectedIndex();
        if(indx == -1)
        {
            JOptionPane.showMessageDialog(null, "Select user to update, Please!", "Err", 1);
            return;
        }
        Users us;
        us = uslist.get(indx);

        UpdateUser up = new UpdateUser(us,df);
        up.setVisible(true);
    }//GEN-LAST:event_bt_updateActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUser au = new AddUser(df);
                au.setVisible(true);
            }
        });
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delActionPerformed
        // TODO add your handling code here:
        int indx = list.getSelectedIndex();
        if(indx == -1)
        {
            JOptionPane.showMessageDialog(null, "Select user to delete, Please!", "Err", 1);
            return;
        }
        Users us;
        us = uslist.get(indx);
        try {
            df.DeleteUser(us.getId());
            JOptionPane.showMessageDialog(null, "User "+ us.getId()+" was deleted!", "Success", 1);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_delActionPerformed

    private void btnAddCompetitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCompetitionMouseClicked
        // TODO add your handling code here:
        Competition competition = new Competition(txtNameCompetition.getText(), Integer.parseInt(txtNumberUser.getText()));
        lstCompetition.add(competition);
        btnRefeshCompetitionMouseClicked(null);
    }//GEN-LAST:event_btnAddCompetitionMouseClicked

    private void btnRefeshCompetitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshCompetitionMouseClicked
        // TODO add your handling code here:
        lstCompetitionList.removeAll();
        for (int i=0; i<lstCompetition.size(); i++)
        {
            String temp;
            if (lstCompetition.get(i).stateCompetition==1)
            {
                temp = " processing...";
            }
            else if (lstCompetition.get(i).stateCompetition==2)
            {
                temp = " end.";
                if (lstCompetition.get(i).userWinner!=null)
                    temp += " Winner is " + lstCompetition.get(i).userWinner.getUsername();
            }
            else
            {
                temp = (lstCompetition.get(i).sumClient - lstCompetition.get(i).lstClient.size()) + " available";
            }
            lstCompetitionList.add(lstCompetition.get(i).strNameCompetition + ": " + temp);
        }
    }//GEN-LAST:event_btnRefeshCompetitionMouseClicked

    private void btnRefeshRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshRoomMouseClicked
        // TODO add your handling code here:
        lstRoomList.removeAll();
        for (int i=0; i<lstRoom.size(); i++)
        {
            lstRoomList.add("Room " + (i+1) + ": Available: " + lstRoom.get(i).countAvailable() + "   \t| Viewer: " + lstRoom.get(i).lstClientView.size());
        }
        lstRoomList.select(0);
    }//GEN-LAST:event_btnRefeshRoomMouseClicked

    private void btnAddRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRoomMouseClicked
        // TODO add your handling code here:
        Room temp = new Room(lstRoom.size()+1);
        lstRoom.add(temp);
        btnRefeshRoomMouseClicked(null);
    }//GEN-LAST:event_btnAddRoomMouseClicked

    private void btnTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopActionPerformed
        // TODO add your handling code here:
        final ArrayList<String> lstTemp = new ArrayList<String>();
        List<Users> us = df.getUserListScoreRank();
        for (Users users : us) {
            lstTemp.add("Id: " + users.getId()
                +" | Username: " + users.getUsername()
                +" | Score:" +users.getScore());
        }
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmDanhSach(lstTemp).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnTopActionPerformed

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        final ArrayList<String> lstTemp = new ArrayList<String>();
        for (ClientHandler cli : lstClient) {
            Users users = cli.user;
            if (users!=null)
            {
                lstTemp.add("Id: " + users.getId()
                    +" | Username: " + users.getUsername()
                    + " | Password: " + users.getPassword()
                    +" | Win:" +users.getWin()
                    +" | Lose:" +users.getLose()
                    +" | Score:" +users.getScore());
            }
        }
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmDanhSach(lstTemp).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnOnlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("SERVER");
                ServerListener server;
                try {
                    server = new ServerListener();
                    server.start();
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                lstClient = new ArrayList<ClientHandler>();
                lstRoom = new ArrayList<Room>();
                for (int i=0; i<10; i++)
                {
                    Room temp = new Room(i);
                    lstRoom.add(temp);
                    
                }
                
                new Main().setVisible(true);
            }
        });
    }

    static class ServerListener extends Thread {

        private ServerSocket serverSocket;

        ServerListener() throws IOException {
            serverSocket = ServerSocketFactory.getDefault().createServerSocket(1234);
        }

        @Override
        public void run() {
            while (true) {
                try {
                    final Socket socketToClient = serverSocket.accept();
                    ClientHandler clientHandler = new ClientHandler(socketToClient);
                    lstClient.add(clientHandler);
                    System.out.println("Server: " + socketToClient.getInetAddress() + " is connecting");
                    clientHandler.start();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_del;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_update;
    private javax.swing.JButton btnAddCompetition;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnOnline;
    private javax.swing.JButton btnRefeshCompetition;
    private javax.swing.JButton btnRefeshRoom;
    private javax.swing.JButton btnTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.List list;
    private java.awt.List lstCompetitionList;
    private java.awt.List lstRoomList;
    private javax.swing.JTextField txtNameCompetition;
    private javax.swing.JTextField txtNumberUser;
    // End of variables declaration//GEN-END:variables
}
