/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package caro.client;

import java.awt.BorderLayout;
import java.awt.Dimension;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import caro.common.CPiece;
import caro.common.GPos;

/**
 *
 * @author Thi
 */
public class OfflineForm extends javax.swing.JFrame {

    JGobanAI Goban;

    JComputerAI Computer;
    
    int GameState = 0;
    final int GS_END = 0;
    final int GS_PLAYUSER = 1;
    final int GS_PLAYCOM = 2;
    final int GS_READY = 3;
    
    int Player[];
    final int HUMAN = 1;
    final int COMPUTER = 2;
    
    int CurrentPlayer;
    final int WHITE = 1;
    final int BLACK = 2;
   
    
    /**
     * Creates new form OfflineForm
     */
    public OfflineForm() {
        initComponents();
        
         setTitle("Game Caro");
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(700, 565);
        
        
        setLayout(new BorderLayout());
        //windowPanel = new PanelBoard(socket);
        //add("Center", windowPanel);
        
        InitGame();
        setLocationRelativeTo(null);
        
    }

    void InitGame() {

        Goban = new JGobanAI();
        Goban.setPreferredSize(new Dimension(500,500));
        
        Computer = new JComputerAI(Goban);
        
        panelCaro.setViewportView(Goban);

        Goban.Sakiyomi = false;
        Goban.Kinjite = false;

        Goban.init(500, 500);
        Goban.Initialize(Computer);
        Goban.Draw();
        
        GameState = GS_READY;
        
        Player = new int[3];
        
        firstButton.setEnabled(true);
        secondButton.setEnabled(true);
        
    }
    void StartGame(int FirstPlayer) {

        if(GameState!=GS_READY)
            return;

        Player[BLACK] = FirstPlayer;
        Player[WHITE] = (FirstPlayer==COMPUTER) ? HUMAN : COMPUTER;
        CurrentPlayer = BLACK;


        firstButton.setEnabled(false);
        secondButton.setEnabled(false);
        clearButton.setEnabled(true);
            //Buttons[i].disable();


        if(FirstPlayer==COMPUTER){
            playerType.setText("O");
            computerType.setText("X");
            Goban.Area[7][7] = 1;
            PlayComputer();
        } else {
            playerType.setText("X");
            computerType.setText("O");
            GameState = GS_PLAYUSER;
        }
    }
    
    void PlayComputer() {

        GPos pos = new GPos();

        putStatus("Computer now thinking...");

        switch(Computer.Think(CurrentPlayer,pos)) {

            case JComputerAI.THINK_OK:

                putStatus("It's now your turn.");
                CurrentPlayer = (CurrentPlayer == WHITE) ? BLACK : WHITE;
                if(Player[CurrentPlayer] == COMPUTER){
                    PlayComputer();
                } else {
                    GameState = GS_PLAYUSER;
                }
                break;

            case JComputerAI.THINK_FILLED:

                putStatus("Board is filled ! Draw game.");
                GameState = GS_END;
                break;

            case JComputerAI.THINK_WIN:

                putStatus("Computer Win !!!");
                GameState = GS_END;
                break;
        }
    }
    void putStatus(String strStt)
    {
        statusLabel.setText(strStt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCaro = new javax.swing.JScrollPane();
        firstButton = new javax.swing.JButton();
        secondButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        computerType = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        playerType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));

        panelCaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCaroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelCaroMouseReleased(evt);
            }
        });

        firstButton.setText("First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        secondButton.setText("Second");
        secondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        statusLabel.setText("Status");

        jLabel2.setText("Player");

        computerType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        computerType.setText("O");

        jLabel4.setText("Computer");

        playerType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerType.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelCaro, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCaro, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(playerType))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computerType)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(secondButton)
                    .addComponent(clearButton)
                    .addComponent(Exit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // TODO add your handling code here:
        StartGame(HUMAN);
    }//GEN-LAST:event_firstButtonActionPerformed

    private void secondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondButtonActionPerformed
        // TODO add your handling code here:
        StartGame(COMPUTER);
    }//GEN-LAST:event_secondButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        InitGame();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void panelCaroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCaroMousePressed
        // TODO add your handling code here:
        int x = evt.getX() - Goban.getX();
        int y = evt.getY() - Goban.getY();
        
        if(GameState==GS_PLAYUSER && Player[CurrentPlayer]==HUMAN) {

            GPos pos = new GPos();
            if( !Goban.GetPos(x,y,pos) )
                return;
            
            switch(Goban.Check(CurrentPlayer, pos.x, pos.y)) {

                case JGobanAI.GC_OK:

                    CurrentPlayer = (CurrentPlayer == WHITE) ? BLACK : WHITE;
                    if(Player[CurrentPlayer] == COMPUTER){
                        GameState = GS_PLAYCOM;
                    }
                    Goban.Draw();
                    break;

                case JGobanAI.GC_ILLEGAL:

                    putStatus("Illegal postion ! Can't put");
                    break;

                case JGobanAI.GC_CANNOT:

                    putStatus("Aleady exist! Can't put");
                    break;

                case JGobanAI.GC_FILLED:

                    putStatus("Board is filled ! Draw game.");
                    GameState = GS_END;
                    break;

                case JGobanAI.GC_WIN:

                    putStatus("You Win !!!");
                    GameState = GS_END;
                    break;
            }
        }
    }//GEN-LAST:event_panelCaroMousePressed

    private void panelCaroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCaroMouseReleased
        // TODO add your handling code here:
        if(GameState == GS_PLAYCOM){
            PlayComputer();
        }
    }//GEN-LAST:event_panelCaroMouseReleased

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OfflineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OfflineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OfflineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OfflineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OfflineForm().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel computerType;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane panelCaro;
    private javax.swing.JLabel playerType;
    private javax.swing.JButton secondButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
