/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package caro.client;

import caro.common.KMessage;
import caro.server.Room;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Cao Ky
 */
public class RoomFrame extends javax.swing.JFrame implements inReceiveMessage{
    ListenServer listenServer;
    /**
     * Creates new form RoomFrame
     */
    public RoomFrame(ListenServer listenServer) {
        initComponents();
        
        setLocationRelativeTo(null);
        this.listenServer = listenServer;
        this.listenServer.receive = this;
        
        setTitle("Game Caro");
        if (listenServer.user!=null)
        {
            setTitle("Game Caro - " + listenServer.user.getUsername());
            lblName.setText("Name: " + listenServer.user.getUsername());
            lblScore.setText("Score: " + listenServer.user.getScore());
            lblWin.setText("Win: " + listenServer.user.getWin());
            lblLose.setText("Lose: " + listenServer.user.getLose());
        }
        try {
            listenServer.SendMessage(21, null);
            listenServer.SendMessage(70, null);
        } catch (IOException ex) {
            Logger.getLogger(RoomFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        btnRefeshOnlineMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new java.awt.Label();
        lblScore = new java.awt.Label();
        lblLose = new java.awt.Label();
        lblWin = new java.awt.Label();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lstRoom = new java.awt.List();
        btnViewRoom = new javax.swing.JButton();
        btnJoinRoom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lstCompetition = new java.awt.List();
        btnRefeshCompetition = new javax.swing.JButton();
        btnJoinCompetition = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lstUserOnline = new java.awt.List();
        btnRefeshOnline = new javax.swing.JButton();
        btnPlayOtherUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setText("Name: Nguyen Cao Ky");

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblScore.setText("Score: 1000");

        lblLose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLose.setText("Lose: 0");

        lblWin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWin.setText("Win: 100");

        btnViewRoom.setText("View Room");
        btnViewRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewRoomMouseClicked(evt);
            }
        });

        btnJoinRoom.setText("Join Room");
        btnJoinRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJoinRoomMouseClicked(evt);
            }
        });

        jButton1.setText("Refesh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJoinRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewRoom)
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lstRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnJoinRoom)
                    .addComponent(btnViewRoom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Room", jPanel3);

        btnRefeshCompetition.setText("Refesh");
        btnRefeshCompetition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefeshCompetitionMouseClicked(evt);
            }
        });

        btnJoinCompetition.setText("Join");
        btnJoinCompetition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJoinCompetitionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnRefeshCompetition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJoinCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lstCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefeshCompetition)
                    .addComponent(btnJoinCompetition))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Competition", jPanel4);

        btnRefeshOnline.setText("Refesh");
        btnRefeshOnline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefeshOnlineMouseClicked(evt);
            }
        });

        btnPlayOtherUser.setText("Play");
        btnPlayOtherUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayOtherUserMouseClicked(evt);
            }
        });
        btnPlayOtherUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayOtherUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lstUserOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefeshOnline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayOtherUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lstUserOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefeshOnline)
                    .addComponent(btnPlayOtherUser))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("User Online", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(lblWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3))
        );

        lblName.getAccessibleContext().setAccessibleName("Name: Nguyen Cao Ky");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            listenServer.SendMessage(21, null);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void btnJoinRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinRoomMouseClicked
        // TODO add your handling code here:
        
        try {
            if (lstRoom.getSelectedIndex()>=0)
            {
                listenServer.SendMessage(20, lstRoom.getSelectedIndex());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnJoinRoomMouseClicked

    private void btnViewRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewRoomMouseClicked
        // TODO add your handling code here:
        
        try {
            if (lstRoom.getSelectedIndex()>=0)
            {
                listenServer.SendMessage(41, lstRoom.getSelectedIndex());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnViewRoomMouseClicked

    private void btnRefeshCompetitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshCompetitionMouseClicked
        // TODO add your handling code here:
        try {
            listenServer.SendMessage(70, null);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnRefeshCompetitionMouseClicked

    private void btnJoinCompetitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJoinCompetitionMouseClicked
        // TODO add your handling code here:
       
        try {
            if (lstCompetition.getSelectedIndex()>=0)
            {
                listenServer.SendMessage(71, lstCompetition.getSelectedIndex());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnJoinCompetitionMouseClicked

    private void btnRefeshOnlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefeshOnlineMouseClicked
        // TODO add your handling code here:
        try {
            listenServer.SendMessage(80, null);    
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnRefeshOnlineMouseClicked

    private void btnPlayOtherUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayOtherUserMouseClicked
        // TODO add your handling code here:
        try {
            if (lstUserOnline.getSelectedIndex()>=0)
            {
                listenServer.SendMessage(81, lstUserOnline.getSelectedItem());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPlayOtherUserMouseClicked

    private void btnPlayOtherUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayOtherUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayOtherUserActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RoomFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RoomFrame(null).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_login1;
    private javax.swing.JButton btnJoinCompetition;
    private javax.swing.JButton btnJoinRoom;
    private javax.swing.JButton btnPlayOffline;
    private javax.swing.JButton btnPlayOffline1;
    private javax.swing.JButton btnPlayOtherUser;
    private javax.swing.JButton btnRefeshCompetition;
    private javax.swing.JButton btnRefeshOnline;
    private javax.swing.JButton btnViewRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private java.awt.Label lblLose;
    private java.awt.Label lblName;
    private java.awt.Label lblScore;
    private java.awt.Label lblWin;
    private java.awt.List lstCompetition;
    private java.awt.List lstRoom;
    private java.awt.List lstUserOnline;
    private javax.swing.JPasswordField tx_password;
    private javax.swing.JPasswordField tx_password1;
    private javax.swing.JTextField tx_username;
    private javax.swing.JTextField tx_username1;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtIP1;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtPort1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ReceiveMessage(KMessage msg) throws IOException {
        switch (msg.getType()) {
            case 20: // get ban co
            {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Main(listenServer).setVisible(true);
                    }
                });
                this.dispose();
                break;
            }
            case 21: {
                lstRoom.removeAll();
                int[] arrRoom = (int[])msg.getObject();
                for (int i=0; arrRoom!=null && i<arrRoom.length; i++)
                {
                    lstRoom.add("Room " + (i+1) + ": " + arrRoom[i] + " available");
                }
                lstRoom.select(0);
                break;
            }
            case 22: { //Room nay da full
                lstRoom.removeAll();
                int[] arrRoom = (int[])msg.getObject();
                for (int i=0; arrRoom!=null && i<arrRoom.length; i++)
                {
                    lstRoom.add("Room " + (i+1) + ": " + arrRoom[i] + " available");
                }
                lstRoom.select(0);
                JOptionPane.showMessageDialog(null, "Room nay da full, lua chon room khac", "Error", 1);
                break;
            }
            case 70:
            {
                lstCompetition.removeAll();
                ArrayList<String> lstCompetitionList = (ArrayList<String>)msg.getObject();
                for (int i=0; lstCompetitionList!=null && i<lstCompetitionList.size(); i++)
                {
                    lstCompetition.add(lstCompetitionList.get(i));
                }
                lstCompetition.select(0);
                break;
            }
            case 71:
            {
                JOptionPane.showMessageDialog(null, "Khong the tham gia vao competition " + msg.getObject().toString(), "Error", 1);
                break;
            }
            case 72:
            {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        new WaitCompetition(listenServer).setVisible(true);
                    }
                });
                this.dispose();
                break;
            }
            case 80: // Hien danh sach online de dau
            {
                lstUserOnline.removeAll();
                ArrayList<String> lstTemp = (ArrayList<String>)msg.getObject();
                if (lstTemp!=null)
                {
                    for (int i=0; i<lstTemp.size(); i++) {
                        lstUserOnline.add(lstTemp.get(i));
                    }
                }
                break;
            }
        
        }
    }
}
